server:
  port: 8083
  tomcat:
    uri-encoding: utf-8

spring:
  mail:
    username: 1329208516@qq.com
    password: gmqyawgqdtkngjcf
    host: smtp.qq.com
    port: 465
    properties:
      mail:
         smtp:
            auth: true
            socketFactory:
               port: 465
               class: javax.net.ssl.SSLSocketFactory
               fallback: false
            starttls:
               enable: true
               required: true
  datasource:
    url: jdbc:mysql://localhost:3306/micm_work_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 5211
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB

  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: update
